In [35]:
import keras
import pandas as pd
from keras.layers import TextVectorization
import numpy as np

In [36]:
df = pd.read_csv('../jigsaw-toxic-comment-classification-challenge/train.csv/train2.csv')

In [37]:
X = df['comment_text']
MAX_FEATURES = 200000
vectorizer = TextVectorization(max_tokens=MAX_FEATURES,
                                    output_sequence_length=1800,
                                    output_mode='int')
vectorizer.adapt(X.values)
        
    # Load ML model
ml_models = keras.layers.TFSMLayer("../notebooks/toxicity", call_endpoint="serving_default")

In [38]:
comment = "Fucking you bitch"

In [45]:
vectorizer

<TextVectorization name=text_vectorization_5, built=True>

In [39]:
input_str = vectorizer(comment)

In [40]:
input_str

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([383,   7, 837, ...,   0,   0,   0], dtype=int64)>

In [41]:
input_tensor = np.expand_dims(input_str, 0).astype(np.float32)

In [42]:
input_tensor

array([[383.,   7., 837., ...,   0.,   0.,   0.]], dtype=float32)

In [43]:
# prediction = (ml_models(np.expand_dims(input_str,0))['output_0'].numpy()> 0.5).astype(int)
prediction = (ml_models(input_tensor)['output_0'].numpy() > 0.5).astype(int)


In [44]:
prediction

array([[1, 1, 1, 0, 1, 0]])